### ISSUE TITLE
Cannot connect to findnacl daemon

### ISSUE THREAD

**Issue by jasoncook** [dnschneid/crouton#2194]
Latest dev-channel release has this repeating error in crosh and xiwi is unable to display a desktop for the chroot.

**ChromeOS Version 47.0.2526.8 dev (64-bit)**

> find_shm: Cannot connect to findnacl daemon. (No such file or directory)
> write_image: Cannot find shm, moving on...
> find_shm: Cannot connect to findnacl daemon. (No such file or directory)
> write_image: Cannot find shm, moving on...
> find_shm: Cannot connect to findnacl daemon. (No such file or directory)
> write_image: Cannot find shm, moving on...

**Comment by jasoncook** [comment]
Manually starting the daemon causes the error to change:

>find_shm: Cannot connect to findnacl daemon. (Connection refused)
write_image: Cannot find shm, moving on...

**Comment by DennisLfromGA** [comment]
Make sure you've updated your chroot with the latest version, there's been some work done on this and it has just recently been merged, see 'Use a daemon to find nacl_helper #2056'

**Comment by jasoncook** [comment]
I've updated to the latest version, but still the same results. Command-line access seems to be unaffected.

**Comment by jasoncook** [comment]
I'm at a loss. I'm not sure what I'm missing. Maybe a permission error?

**Comment by DennisLfromGA** [comment]
I'm not sure either unfortunately; I don't know if this is just now cropping up with the latest changes made to the find ncal_helper routine or not. Maybe one of the developers can help.

**Comment by jasoncook** [comment]
I installed a fresh chroot. Same issue. I will try a different build-channel.

**Comment by jasoncook** [comment]
Latest Stable-Channel does not give the nacl error. So it would seem to be something different in the ChromeOS Dev-Channel that causes this to break. Maybe @drinkcat or @dnschneid can take a look at some point.

**Comment by jasoncook** [comment]
I do see the following message, however it does not repeat and the desktop is displayed correctly.

>recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.

**Comment by dnschneid** [comment]
@drinkcat: something about dev broken findnacld?

**Comment by drinkcat** [comment]
I'll have a look. No idea.

**Comment by jasoncook** [comment]
I switched back to Dev-Channel and I no longer see the error. So either it was an issue in ChromeOS that's been fixed in the most recent build or the powerwash fixed some broken permissions somewhere. Thank you for your all the work you've put into this project.

**Version 48.0.2541.0 dev (64-bit)**

**Comment by sgosnell** [comment]
I've been getting it for about a week.  I just updated ChromeOS to the latest dev channel release (they're getting very frequent), updated the chroot, and still have this issue.  Can't run the chroot.

**Comment by jasoncook** [comment]
@sgosnell, could you see if the problem persists after a **powerwash**?

**Comment by sgosnell** [comment]
I don't want to do a powerwash just for this.  I just noticed that a chromebook I rarely use still works.  I just started an update to crouton to see what happens.  I'm pretty sure the version it was running was from before the nacl daemon was introduced.  We'll see what happens after the update finishes.

**Comment by sgosnell** [comment]
Any news on this?  Crouton still won't run for me.  Just updated to the latest dev channel update, and still get the "cannot connect to findnacl daemon" error.

**Comment by jasoncook** [comment]
I updated to the latest dev build today. I haven't seen the error since I toggled build channels a week ago.

**Comment by dnschneid** [comment]
@sgosnell are you still seeing this on the latest beta?

**Comment by sgosnell** [comment]
Don't know about beta, I've been on dev channel for more than a year.  But yes, I'm seeing it on the latest dev channel update.  Curiously, I haven't had the issue on my Acer C720, only on my Asus chromebox.  I just did an update to the Jessie chroot, and have the latest CrOS Dev channel update running.  It still can't connect to findnacl daemon.

**Comment by drinkcat** [comment]
@sgosnell : Can I have the output of `croutonversion` on both your C720 and Chromebox?

@jasoncook : Can I have that output too? (it's ok if its on a working version: I'm not sure which Chromebook you are using)

In all cases, can I also have the output of `ls -l /var/run/crouton-ext`?

Thanks!

**Comment by sgosnell** [comment]
On the C720:
(jessie)stan@localhost:~$ croutonversion 
crouton: version 1-20151013174138~master:488c9e21
release: jessie
architecture: amd64
xmethod: xiwi
targets: xfce,xiwi
host: version 7583.0.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Sun Oct 25 19:55:57 PDT 2015 x86_64 GNU/Linux
freon: yes

(jessie)stan@localhost:~$ ls -l /var/run/crouton-ext           
total 0
srwxrwx--- 1 root video 0 Nov  3 14:11 socket

I can't run these on the chromebox, because I can't get into the chroot.  If you know of another way, let me know.

**Comment by sgosnell** [comment]
On the C720:

(jessie)stan@localhost:~$ croutonversion

crouton: version 1-20151013174138~master:488c9e21

release: jessie

architecture: amd64

xmethod: xiwi

targets: xfce,xiwi

host: version 7583.0.0 (Official Build) dev-channel peppy

kernel: Linux localhost 3.8.11 #1 SMP Sun Oct 25 19:55:57 PDT 2015 x86_64
GNU/Linux

freon: yes


(jessie)stan@localhost:~$ ls -l /var/run/crouton-ext

total 0

srwxrwx--- 1 root video 0 Nov 3 14:11 socket


I can't run these on the chromebox, because I can't get into the chroot. If you
know of another way, let me know. FWIW, I downloaded the latest crouton script
from here, again, just now and still have the same issue.


The CrOS data of the chromebox:

Version 48.0.2546.0 dev (64-bit)

Platform 7583.0.0 (Official Build) dev-channel panther

Firmware Google_Panther.4920.24.26


From a terminal in CrOS on the chromebox:

chronos@localhost ~/Downloads $ sudo ls -l /var/run/crouton

total 0

drwxr-xr-x 3 root root 60 Nov 3 14:15 media


There is no crouton-ext directory, and none in the chroot.




Regards,

Stan

On Tue, Nov 03, 2015 at 6:24 PM, drinkcat < notifications@github.com [notifications@github.com] > wrote:
@sgosnell [https://github.com/sgosnell] : Can I have the output of croutonversion on both your C720 and Chromebox?

@jasoncook [https://github.com/jasoncook] : Can I have that output too? (it's ok if its on a working version: I'm not
sure which Chromebook you are using)

In all cases, can I also have the output of ls -l /var/run/crouton-ext ?

Thanks!

—
Reply to this email directly or view it on GitHub
[https://github.com/dnschneid/crouton/issues/2194#issuecomment-153532389] .[https://github.com/notifications/beacon/AKfzN2FaMLXUz-plp-0bDiYOJKklHHdNks5pCUeugaJpZM4GPfoX.gif]

**Comment by jasoncook** [comment]
@sgosnell can you get to the chroot on the Chromebox without loading xfce? When I first reported this issue command-line access was still possible for me.

I'm using an old Toshiba Chromebook 1.
>(sana)root@localhost:~# croutonversion 
crouton: version git
release: sana
architecture: amd64
xmethod: xiwi
targets: xiwi,xfce
host: version 7604.0.0 (Official Build) dev-channel leon 
kernel: Linux localhost 3.8.11 #1 SMP Sun Nov 1 21:41:53 PST 2015 x86_64 GNU/Linux
freon: yes

>(sana)root@localhost:~# ls -l /var/run/crouton-ext
total 0
srwxrwx--- 1 root video 0 Nov  4 09:31 socket

**Comment by sgosnell** [comment]
Partly on a hunch, and partly because I like Sid, I did a dist-upgrade to Sid from Jessie, via the command line in the chroot.  I was hoping for improvement, but things are still the same, 

find_shm: Cannot connect to findnacl daemon. (No such file or directory)
write_image: Cannot find shm, moving on...
find_shm: Cannot connect to findnacl daemon. (No such file or directory)
write_image: Cannot find shm, moving on...

until halted by Ctrl-C.

**Comment by sgosnell** [comment]
I tried reverting to both beta and stable channels, but that had no effect.  I've powerwashed at least half a dozen times, and that doesn't help either.

**Comment by drinkcat** [comment]
Sorry for the delay...

Can you try running this in the chroot, see if it outputs any error : `/usr/local/bin/croutonfindnacld`

**Comment by sgosnell** [comment]
I had about forgotten about this. I've wiped CrOS entirely, and now I'm running
Debian natively on my chromebox. I'm afraid I won't be much help going forward.
I still have crouton on a chromebook, but it doesn't have the problem.


Regards,

Stan

On Wed, Nov 18, 2015 at 8:07 AM, drinkcat < notifications@github.com [notifications@github.com] > wrote:
Sorry for the delay...

Can you try running this in the chroot, see if it outputs any error : /usr/local/bin/croutonfindnacld

—
Reply to this email directly or view it on GitHub
[https://github.com/dnschneid/crouton/issues/2194#issuecomment-157722915] .[https://github.com/notifications/beacon/AKfzN9LXzId_wfk_tLIll4D8H92Gu6xiks5pHH2ZgaJpZM4GPfoX.gif]

**Comment by berdario** [comment]
I just got the same error, so I guess this happens at the best time for this bug not to be lost :)

I have an Ubuntu wily chroot. I'm using the chromeos terminal extension and the Atom editor on xiwi.
I got interested into running a normal environment, since the normal environment doesn't cut it... I have the following problems (maybe someone can suggest?):

- the terminal chrome extension doesn't have tabs, at the moment I'm working around it with byobu/tmux, but then the scrollback doesn't work well anymore with via scrolling
- LANG is not set, this causes my git prompt to break up (this can be easily fixed, but it should also be taken care of by a proper desktop session... xfce or whatever)
- vi is a bit borked up: cursor keys print letters while in insert mode for that (found a solution), backspace leaves the letters printed (but they'll be overwritten while writing new chars) and search+{left, up} which usually yields a key like HOME or PgUp prints letters (just like it was for the cursor keys). I have even tried with lxterminal on xiwi, but it seems even worse (vi doesn't display some terminal codes correctly)

So, I checked by comparing the enviroment with a normal Ubuntu system, if aside from `LANG` there could be another difference, but I couldn't find anything interesting. I decided to try with `startxiwi dbus-launch gnome-terminal` and I got this error

Then, I installed the xfce target, and I got again the error when running `startxfce`

    > sudo /usr/local/bin/croutonfindnacld
    main: Failed to bind address: /var/run/crouton-ext/socket. (Address already in use)

Inside the chroot:
    > cat /etc/group | grep video
    video:x:27:dario

outside the chroot:

    chronos@localhost / $ cat /etc/group | grep video
    video:!:27:root,chronos

**Comment by drinkcat** [comment]
@berdario : Can you provide the output of croutonversion please?

**Comment by berdario** [comment]
@drinkcat

    > croutonversion 
    crouton: version 1-20151104200003~master:2a1fc9da
    release: wily
    architecture: amd64
    xmethod: xiwi
    targets: xfce,xiwi,extension,cli-extra
    host: version 7390.68.0 (Official Build) stable-channel auron_yuna 
    kernel: Linux localhost 3.14.0 #1 SMP Thu Nov 5 13:23:54 PST 2015 x86_64 x86_64 x86_64 GNU/Linux
    freon: yes

**Comment by drinkcat** [comment]
Was not able to reproduce with this config:
```
Entering /mnt/stateful_partition/crouton/chroots/jessie...
crouton: version 1-20151104200003~master:2a1fc9da
release: jessie
architecture: amd64
xmethod: xiwi
targets: xiwi
host: version 7632.0.0 (Official Build) dev-channel panther test
kernel: Linux localhost 3.8.11 #1 SMP Wed Nov 11 04:04:24 PST 2015 x86_64 GNU/Linux
freon: yes
```

@berdario : What exact command are you using when you hit this issue?

**Comment by berdario** [comment]
I used `startxiwi dbus-launch gnome-terminal`... and the problem also appeared with `startxfce4`. I assume that every program that relied on X would've failed in that way.

Since that prevented me from doing stuff, I rebooted and managed to open xfce. Now when I try again the same I don't get the original

```find_shm: Cannot connect to findnacl daemon. (No such file or directory)
write_image: Cannot find shm, moving on...```

error... 

If I stumble upon it again, or I'll find a way to reproduce it deterministically, I'll update here

**Comment by sgosnell** [comment]
This is back for me.  It only happens when I try to run the chroot from an SD card.  Running it from the internal SSD works, but it can't find the nacldaemon from the SD card.

**Comment by PIDedl1973** [comment]
I am also having this issue. I'm using an Asus Flip chromebook. Here is my croutonversion
crouton: version 1-20151104200003~master:2a1fc9da
release: sana
architecture: armhf
xmethod: xiwi
targets: xfce,xiwi
host: version 7647.18.0 (Official Build) dev-channel veyron_minnie 
kernel: Linux localhost 3.14.0 #1 SMP Wed Dec 2 23:40:57 PST 2015 armv7l GNU/Linux
freon: yes

**Comment by sgosnell** [comment]
FWIW, I get this when starting the chroot:

chronos@localhost / $ sh ~/Downloads/startdeb
Password: 
Entering /media/removable/SD Card/chroots/sid...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.17.3
Release Date: 2015-10-26
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed Dec 2 22:01:18 PST 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=cb449268-c814-df41-b8ac-ec1221fb7e7b/PARTNROFF=1 hashtree=PARTUUID=cb449268-c814-df41-b8ac-ec1221fb7e7b/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=45d4bbde3fa1ffc1dfb38dcdac88498b34c3fa1d salt=38de8fa2bf862e7a5a6bc36f6f42e664a67f4fdab13c2b69bb92def4bfc7b5a2" noinitrd vt.global_cursor_default=0 kern_guid=cb449268-c814-df41-b8ac-ec1221fb7e7b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 27 October 2015  11:41:02PM
xorg-server 2:1.17.3-2 (http://www.debian.org/support) 
Current version of pixman: 0.33.4
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Tue Dec  8 18:47:38 2015
(++) Using config file: "/etc/X11/xorg-dummy.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
/usr/bin/xinit: XFree86_VT property unexpectedly has 0 items instead of 1

It then tries to start the chroot, and repeats the "can't find nacldaemon" ad infinitum.


(sid)stan@localhost:~$ croutonversion
crouton: version 1-20151104200003~master:2a1fc9da
release: sid
architecture: amd64
xmethod: xiwi
targets: extension,xiwi
host: version 7647.18.0 (Official Build) dev-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Dec 2 22:01:18 PST 2015 x86_64 GNU/Linux
freon: yes

**Comment by DennisLfromGA** [comment]
@sgosnell,
What is the content of your `~/Downloads/startdeb` command?

You should also be able to start it using something like: 

`sudo /media/removable/SD Card/bin/startxfce4 -n sid`

and see if you still have the same "can't find nacldaemon" errors.

Your chroot looks a little strange in that you're running 'startxfce4' but yet your 'targets:' don't reflect it...

**Comment by sgosnell** [comment]
I'm not sure why xfce isn't reflected there.  It has been installed since the chroot was installed.  All worked fine until an update broke things, as indicated in my first post.  The contents of startdeb are:

sudo sh /media/removable/SD\ Card/host-bin/enter-chroot -c /media/removable/SD\ Card/chroots startxfce4 -b

If I just use the simpler method you posted, I get a "permission denied" error, always have.  I'm not sure why, I've set the permissions of everything in /media/removable/SD Card/bin, with no change.  I may have things in places they're not supposed to be, but everything worked for months before the update broke it.

**Comment by DennisLfromGA** [comment]
@sgosnell - Before you bite the bullet and wipe the chroot, take a look at Issue https://github.com/dnschneid/crouton/issues/2176#issuecomment-147473247 and it's resolution, it may be similar to yours.

**Comment by divx118** [comment]
@sgosnell 
 > If I just use the simpler method you posted, I get a "permission denied" error, always have. I'm not sure why, I've set the permissions of everything in /media/removable/SD Card/bin, with no change. 

FYI by default external media is mounted with the noexec flag on chromeos. So to use the simpler command and thus have exec rights you have to remount the SD card. This however doesn't solve your issue ...

**Comment by DennisLfromGA** [comment]
Thanx @divx118, I forgot about that...
So maybe this'll work but won't solve his 'find nacldaemon' problem:
`sudo sh /media/removable/SD Card/bin/startxfce4 -n sid`

I wonder thought if having exec rights on the SD Card just might be part of the problem???

**Comment by sgosnell** [comment]
Well, not it's working.  I deleted the jessie chroot from my SSD, and used
sudo enter-chroot -c /media/removable/SD\ Card/chroots startxfce4

and the X system works, the nacl daemon is apparently found.  I think the problem is with the directory structure.  Running enter-chroot from the SD card doesn't work, for whatever reason.  Now I only wonder why something that worked for a long time suddenly broke.  Probably the nacl daemon changed things.  In any case, I think this may be solved now.

**Comment by DennisLfromGA** [comment]
Well it's good to know you found a solution, sorry you had to delete your chroot.
It seems to be a problem peculiar to external media but I don't know why.
I'm not sure if it became an issue with the latest changes 'Use a daemon to find nacl_helper #2056' or if there was a problem with external media before.
Hopefully it'll continue to work for you and won't *break* again - fingers crossed...

**Comment by sgosnell** [comment]
I had planned to delete the chroot on the internal SSD anyway, as soon as I got the one on the SD card working.  I didn't have much there due to storage space considerations, that's why I'm using the SD.  I have extra 32GB SD cards, and this one has the chroot from my chromebox on it.  I deleted CrOS from the chromebox and am running straight Debian on it, so I don't need the chroot there, but it's nice to be able to have it on my chromebook.  I had the exact same symptoms on the chromebox, which is one reason I deleted CrOS from it.  I don't need the quick boot-time and the rest of CrOS on a desktop.

**Comment by grandrew** [comment]
Same issue here, Haier chromebook

```
crouton: version 1-20160902144033~master:9f8e9a22
release: trusty
architecture: armhf
xmethod: xiwi
targets: xiwi,xfce
host: version 8530.81.0 (Official Build) stable-channel veyron_jaq 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed Sep 7 16:44:33 PDT 2016 armv7l armv7l armv7l GNU/Linux
freon: yes
```

also from SD card

can somebody explain how is this supposed to work? I can dig into this issue

**Comment by avm99963** [comment]
Hi!

I'm having the same issue, but I'm running crouton in a Chromium OS build (a special build by [ArnoldTheBat](https://chromium.arnoldthebat.co.uk/)). I don't have any problem running the chroot with Xorg, but when running it with Xiwi using the command `sudo startxfce4 -X xiwi` I get the following error messages (the same as the OP):

```
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
```

These keep being printed in the terminal until I stop the command manually.

Here's the output of `croutonversion`:

```
crouton: version 1-20161129162558~master:5f2f11f9
release: trusty
architecture: i386
xmethod: xorg
targets: xorg,xfce,xiwi
host: version 8777.0.2016_10_30_1349 (Developer Build - tonyd) developer-build x86-atb
kernel: Linux localhost 4.4.14-05594-g97ec5cc #1 SMP PREEMPT Sun Oct 30 09:46:12 GMT 2016 i686 i686 i686 GNU/Linux
freon: no
```

The  Chromium OS version is 55.0.2853.0 (32-bit).

If you need any help troubleshooting this issue in order to solve it, ask me anything please :)

Thanks!

**Comment by avm99963** [comment]
Woops, I forgot to mention the following:

When running `/usr/local/bin/croutonfindnacld`, I get the following:

> main: Cannot set gid to 27 (Operation not permitted)

And after running it with sudo (`sudo /usr/local/bin/croutonfindnacld`), I get:

> main: Failed to bind address: /var/run/crouton-ext/socket. (Address already in use)

**Comment by howard3718** [comment]
Hi, I'm trying to run crouton on my old dell windows pc that I converted to chromium using neverware's cloudready system and am getting the same repeating error of 

```
Connected to extension, launched crouton in a window.
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
write_image: Cannot find shm, moving on...
recv_pid_fd: No fd is passed from findnacl daemon.
```
I can enter chroot but cannot launch unity, as i keep getting this looping bug. Haven't yet tried wiping unity and trying xfce
output of ```croutonversion``` is
```
(precise)howard@localhost:~$ croutonversion
crouton: version 1-20170228132702~master:21cb695b
release: precise
architecture: i386
xmethod: xiwi
targets: unity,xiwi
host: version 55.2.57 (Developer Build - neverware) developer-build chromeover32
kernel: Linux localhost 4.4.14+ #1 SMP Wed Mar 1 02:16:07 UTC 2017 i686 i686 i386 GNU/Linux
freon: no
```
output of ```/usr/local/bin/croutonfindnacld``` when in crouton is 
```
Cannot set gid to 27 (Operation not permitted)
```
and output of ``` cat /etc/group | grep video``` is
```
video:x:27:howard
```

Cheers in advanced

**Comment by Newtsrock** [comment]
I of course have the same issue, but I think it is due to chrome 56 as mentioned here: https://github.com/dnschneid/crouton/issues/2917

**Comment by ryanphjohnson** [comment]
I just ran into this issue. I'm running:
Chromebook Pixel LS 2015
Version 58.0.3029.140 (64-bit)
Platform 9334.72.0 (Official Build) stable-channel samus
ARC Version 4015103
Firmware Google_Samus.6300.174.0

name: signal
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/signal...
crouton: version 1-20170315143304~master:95589555
release: trusty
architecture: amd64
xmethod: xiwi
targets: xfce,xfce-desktop,xiwi,cli-extra,keyboard,x11,core,audio,touch,xorg
host: version 9334.72.0 (Official Build) stable-channel samus 
kernel: Linux localhost 3.14.0 #1 SMP PREEMPT Wed May 17 18:08:22 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

Would really love it if someone could post their solution 👍

**Comment by ryanphjohnson** [comment]
Nevermind, after a reboot, everything seems to be working again. Thanks

**Comment by The1andONLYdave** [comment]
Getting this when starting wesnoth ( https://www.wesnoth.org/ ) with -w (window mode) via xiwi. 
Xorg target is running fine.
Other windowed apps in xiwi running fine.
Wesnoth in normal (fullscreen) is terminating instantly after 18x findnacl daemon error:

```
find_shm: Cannot connect to findnacl daemon. (Connection refused)
write_image: Cannot find shm, moving on...
20171115 20:16:56 warning font: Failed opening font file 'DroidSansJapanese.ttf': No such file or directory
20171115 20:16:56 warning font: Failed opening font file 'DroidSansFallbackFull.ttf': No such file or directory
Checking video mode: 1366x768x32...
setting mode to 1366x768x32
find_shm: Cannot connect to findnacl daemon. (Connection refused)
write_image: Cannot find shm, moving on...
15.11.2017 20:16:56 - ERROR: No output found at destination coordinates, centering floating window on current ws
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x296
  Serial number of failed request:  129
  Current serial number in output stream:  131
find_shm: Cannot connect to findnacl daemon. (Connection refused)
write_image: Cannot find shm, moving on...
Running exit commands...
/usr/bin/xinit: connection to X server lost
```

Any ideas?
Running latest crouton on latest (stable) ChromeOS on cyan.

**Comment by pcouy** [comment]
I'm having the same issue : 

```
recv_pid_fd: No fd is passed from findnacl daemon.
find_shm: Cannot open nacl file.
```

```
(trusty)root@localhost:~# croutonfindnacld 
main: Failed to bind address: /var/run/crouton-ext/socket. (Address already in use)
```

```
(trusty)root@localhost:~# croutonversion
crouton: version unknown
release: unknown
architecture: unknown
xmethod: xiwi
targets: audio,xiwi,xfce,cli-extra,keyboard,touch,x11,xorg
host: version 10176.5.0 (Official Build) dev-channel cyan 
kernel: Linux localhost 3.18.0-16346-g4ffebefcbbdb #1 SMP PREEMPT Wed Dec 6 02:36:52 PST 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes```

Everything worked fine until I updated ChromeOS to Version 64.0.3282.11 dev 64bits

**Comment by hoosierEE** [comment]
I think I have the same issue.  Just updated chroot with xiwi, and the **first time** I launched `sudo startxiwi xterm` it worked.  Every time after that, I get stuck in the infinite loop of 

```
find_shm: Cannot connect to findnacl daemon. (Connection refused)
write_image: Cannot find shm, moving on...
find_shm: Cannot connect to findnacl daemon. (Connection refused)
write_image: Cannot find shm, moving on...
find_shm: Cannot connect to findnacl daemon. (Connection refused)
write_image: Cannot find shm, moving on...
find_shm: Cannot connect to findnacl daemon. (Connection refused)
write_image: Cannot find shm, moving on...
```

My croutonversion:

```
lx@~/Downloads croutonversion
crouton: version 1-20181001133934~master:38012fdf
release: xenial
architecture: arm64
xmethod: xiwi
targets: xiwi,cli-extra
host: version 11151.59.0 (Official Build) stable-channel elm 
kernel: Linux localhost 3.18.0-18720-g7b8c1dc67cda #1 SMP PREEMPT Mon Dec 10 23:51:35 PST 2018 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
```

**Comment by TheTechRobo** [comment]
For me it worked until last night when my chromebook was close to dying. I plugged it in right before (it was in sleep mode) and it hasn't worked since. I'm going to try a restart.
