### ISSUE TITLE
crouton switching rapidly between chromeOS and crouton since chromeOS update 

### ISSUE THREAD

**Issue by kajodowe** [dnschneid/crouton#2576]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20160420122426~master:46f3c372
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,lxde
host: version 7978.66.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 27 11:10:19 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Not unmounting /mnt/stateful_partition/crouton/chroots/trusty as another instance is using it.

#### Please describe your issue:

Since last chromeOS update, crouton switches rapidly between chromeOS and crouton. 
per this link: https://www.reddit.com/r/Crouton/comments/4ijjls/since_last_chromeos_update_crouton_switches/

**Comment by kajodowe** [comment]
After writing this I searched other issues here and upgraded to Version 51.0.2704.37 beta (64-bit. Problem seems to be solved but haven't evaluated fully yet.

**Comment by davidlowryduda** [comment]
I believe this is the same issue as reported in https://github.com/dnschneid/crouton/issues/2564 and https://github.com/dnschneid/crouton/issues/2559 but there does not yet seem to be a known fix. The reddit thread you link to mentions something, but it did not work for me nor many others [nor should it work]. For me there is no problem immediately after a reboot (which I suspect is making the reddit thread a bit convoluted, since they recommend rebooting). But once I let my machine sleep and then reawaken it, the flicker returns.

For now, I've activated the xiwi target and use crouton-as-a-window. [Interestingly, X recently updated their certificate, so this is out of date. I had to disable the autocheck to install the xiwi target]. Functionally, this allows me to do almost everything exactly as before, with the exception of a few SuperL remaps that became necessary.

**Comment by kajodowe** [comment]
Thanks David. I can't guarantee my flicker won't return but it's been almost 24 hours since I changed to beta channel with Chrome OS and I have not seen any flicker. I didn't know you could use crouton-as-a-window! I love being able to switch over from Chrome to Linux but your approach is very interesting. I used LInux before I got my Chromebook but Crouton has made my Chromebook so much more valuable! I love it!

Take care.

**Comment by wkhalidman2** [comment]
I have the exact same issue as David here, and is there any way to make the flicker stop when you come cack to out  of sleep mode? It's been kind of tedious to reboot over and over again. I'm not a very good fan of crouton integration, since my linux gets laggy. Running trusty xfce.

**Comment by kajodowe** [comment]
Hi -- I thought I had the problem solved but I did have flickering last night. Nothing today so far. I am not a crouton/linux expert by any means. Wish I could help you more! I am running LXDE rather than XFCE -- I don't have much lag but I do mainly lightweight tasks on linux (browsing, word processing, spreadsheets and reading ebooks). If I hear anything I will let you know.

**Comment by roger77** [comment]
I think I have the same issue. 

$ croutonversion crouton: version 1-20160420122426~master:46f3c372 release: trusty architecture: amd64 xmethod: xorg targets: xorg,x11,extension,unity,unity-desktop,xiwi,touch host: version 7978.66.0 (Official Build) stable-channel link kernel: Linux localhost 3.8.11 #1 SMP Wed Apr 27 15:27:04 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux freon: yes

**Comment by wkhalidman2** [comment]
I guess it's laggy cause I use linux to play a lot of games, and I use wine as well. But the flickering has to do something with sleepmode, cause if you reboot it's fine, but sleep mode (chromebook) ruins it.

**Comment by kajodowe** [comment]
I may post something in this forum: https://groups.google.com/forum/#!forum/crouton-central but I think that the problem is best addressed here. Hopefully we'll find a solution!

**Comment by flactemnad** [comment]
I've switched my ChromeOS channel from stable to beta and that has fixed the flashing screen focus.  My system is running very slow overall now, but at least it's not flashing!  I can live with this until Chrome gets it's next update.

**Comment by wkhalidman2** [comment]
have you tried going into sleep mode then running linux?

**Comment by flactemnad** [comment]
Yes, after switching to the beta channel I'm now running Version 51.0.2704.42 beta (64-bit), and that doesn't seem to have the problems that the previous V50 did for me.  Putting the system to sleep, resuming and then switching to Linux or any variation of sleeping seems to be more stable at this time.

This was only a problem for me after the last ChromeOS update on the stable channel, so I think something is amiss in that release.  For now, the beta channel will be my workaround.

**Comment by kajodowe** [comment]
flactemnad and wkhalidman2 -- I too am stil on Beta channel and except for one brief interval -- no flickering and no problem with sleep mode. The only watchout is (as I understand it) that if you switch  back from Chrome Beta to Chrome Stable then you lose all your data. Is that correct? Does that mean you would lose all the Crouton setup? I do backups of Crouton and Chrome but it would still be a pain to lose everything!

**Comment by wkhalidman2** [comment]
I'll just leave switching to beta channel as a last resort, I'd rather just wait a bit for the solution. For now, just find a way to keep linux alone for while. Don't worry, the solution will come. If not, we should call in one of the big devs or something.

**Comment by CoredusK** [comment]
Is there nothing we can do besides switching to beta channel?

**Comment by kajodowe** [comment]
CoredusK -- this should be the place to fix it. It is my understanding that David Schneider is the author/creator of Crouton and that he checks in here pretty regularly. This is the 'official' home of Crouton. Hopefully we'll know something soon.

**Comment by wkhalidman2** [comment]
If there's anyone who can fix this, it's got to be dnschneid

**Comment by fjribal** [comment]
You are not alone, same here, Acer C720,  

ChromeOS version: 50.0.2661.91
version 7978.66.0 (Official Build) stable-channel peppy
crouton: version 1-20151104200003~master:2a1fc9da

When logged in xfce (precise trusty) it changes intermittently between both systems.

I haven't tried the beta one.

**Comment by wkhalidman2** [comment]
Today, there was a new update of chrome os. Tried running linux after sleep mode, but the problem still remains.

**Comment by Kalirren** [comment]
It seems like everyone who is having this problem (myself included, see #2580) is using a Acer C720 or C720P.  Is there anyone using different hardware who is also having this problem?

**Comment by acowley** [comment]
I see the problem on an HP Chromebox CB1-014.

**Comment by adamlsd** [comment]
Seen on an HP Chromebook 11 (Model CB2, ARM Exynos board).

	
SPRING G9A-D3J-A8D
SAMSUNG EXYNOS5 (Flattened Device Tree)

The system will not stay in the chroot-X11 for more than about 3 to 5 seconds.  Sometimes it switches much more quickly than that.

**Comment by spafindoople** [comment]
Having the same problem on Chromebook Pixel.

**Comment by djreiss** [comment]
Same issue on a c720 and trusty. Just started after a (forced) ChromeOS upgrade.

Chrome OS:
Version 50.0.2661.103 (64-bit)
Platform 7978.74.0 (Official Build) stable-channel peppy
Firmware Google_Peppy.4389.93.0

name: trusty
encrypted: no
Entering /usr/local/chroots/trusty...
crouton: version 1-20160330180425~master:43e2fca0
release: trusty
architecture: amd64
xmethod: xorg
targets: keyboard,audio,extension,gtk-extra,core,cli-extra,xorg
host: version 7978.74.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 11 22:25:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes

**Comment by floe** [comment]
Happened to me with xfce-desktop on xenial and an Asus Chromebook Flip. Seems to be gone after upgrading ChromeOS to current beta channel.

**Comment by roger77** [comment]
Happened to me on a 2013 Pixel. Gone now with latest upgrade to current stable-channel

**Comment by djreiss** [comment]
Still happening to me on the latest ChromOS stable. I have no upgrade available.

**Comment by shwnchpl** [comment]
Same problem here on an Acer C720P.

`(precise)moth@localhost:~/Programming$ croutonversion 
crouton: version 1-20160518095657~master:fd37bb79
release: precise
architecture: amd64
xmethod: xorg
targets: extension,touch,xfce
host: version 7978.74.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 11 22:25:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
`

It does seem to have something to do with whether or not the page that one had loaded in Chrome had processing running in the background.  For instance, attempting to switch over using CTRL+ALT+SHIFT+F2 from a page like Facebook will lead to severe flickering, while switching over from this page will not (except for when I am in the middle of entering text, for some reason).  Also, whenever a Facebook notification occurs in ChromeOS, flickering occurs.  For now I'll be trying to switch over from relatively inert pages and hoping for the best.

**Comment by flactemnad** [comment]
My Acer C720P was experiencing the same issue.  Since switching to the beta I've only had a similar issue once: Version 51.0.2704.55 beta (64-bit), Platform 8172.39.0 (Official Build) beta-channel peppy, Firmware Google_Peppy.4389.93.0

**Comment by darethehair** [comment]
I guess I am also hoping for whatever solution present itself, but I have an even more confusing situation: I have *two* Acer C720P chromebooks -- both at the same version of everything -- and my older one is fine, but the newer one has the flipping/flickering!

A bit more detail: I made a crouton backup of the 1st one, and restored it into the 2nd one.  Version of Chrome OS is also the same.  Not sure if it is relevant, but while starting the 'bad' one, I get an additional set of errors that are not in the first:

`gnome-keyring-daemon: insufficient process capabilities, unsecure memory might get used`

Yes, I am confused as to why one of them works, and the other does not.

**Comment by djreiss** [comment]
@shwnchpl I observe the same thing - with the active Chrome tab on a page with few updates, I see fewer flickers. When I had the Chrome tab on the terminal from which I started x11 via `xinit`, I was seeing lots of flickering because of the continual text output to the terminal window.

**Comment by dnschneid** [comment]
Really sorry for being MIA on this.  Are people still running into this issue, or did it get fixed with the latest stable update/updating your chroot/rebooting?

**Comment by jejones3141** [comment]
I grabbed crouton this past weekend and set it up for xenial using e17.
It's still switching. At first I thought it was influenced by my using the
touchpad, but I found that I could just let it sit there and it would still
switch back and forth. Here's the info on my Chromebook (an Acer C720) and
the ChromeOS version it's using:

version 50.0.2661.103 (64-bit)
platform 7978.74.0 (official build) stable-channel peppy
firmware Google_Peppy 4389.93.0

**Comment by kkelley515** [comment]
Having the same issue on an HP Chromebook 14. Issue still persists after updating the chroot.

FWIW, I believe the flicker happens any time a message is written to the crosh shell where the chroot was launched from.

**Comment by fjribal** [comment]
Hi,

the problem remains.

I took it as a sign and upgraded to Trusty.

With xiwi it works fin, but with xorg the flickering goes on.

Some suggested some kind of pattern depending on the background page, I haven't noticed that, for me it seems quite random.

I just updated the chroot and launched trusty xfce again. 
I have full access to xfce but there is random flickering.

This is what the terminal is currently showing (hope it helps, thank you)



chronos@localhost / $ sudo startxfce4
Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed May 11 22:25:37 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4aa30189-29c0-1640-af81-1abb4eb40031/PARTNROFF=1 hashtree=PARTUUID=4aa30189-29c0-1640-af81-1abb4eb40031/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=9536469a974cd2ac0ebb87562ea3f36bfc24b230 salt=223aff6112c638e9287e73d93ce67a8d48776f5036c70650c7573a52e259b4cc" noinitrd vt.global_cursor_default=0 kern_guid=4aa30189-29c0-1640-af81-1abb4eb40031 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jun  9 18:40:42 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi
host: version 7978.74.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 11 22:25:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:26566): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:26566): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
Timeout waiting for extension to connect.
Cannot open /sys/class/tty/tty0/active: No such file or directory
croutonwebsocket error: Error: not connected.(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
croutonwebsocket error: EError: not connected.(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
croutonwebsocket error: EError: not connected.

Password: 
Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.2.0-76-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Wed May 11 22:25:37 PDT 2016 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=4aa30189-29c0-1640-af81-1abb4eb40031/PARTNROFF=1 hashtree=PARTUUID=4aa30189-29c0-1640-af81-1abb4eb40031/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=9536469a974cd2ac0ebb87562ea3f36bfc24b230 salt=223aff6112c638e9287e73d93ce67a8d48776f5036c70650c7573a52e259b4cc" noinitrd vt.global_cursor_default=0 kern_guid=4aa30189-29c0-1640-af81-1abb4eb40031 add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:29PM
xorg-server 2:1.15.1-0ubuntu2.7 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Thu Jun  9 18:40:42 2016
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension Present
Initializing built-in extension DRI3
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
crouton: version 1-20160518095657~master:fd37bb79
release: trusty
architecture: amd64
xmethod: xorg
targets: xorg,xfce,xiwi
host: version 7978.74.0 (Official Build) stable-channel peppy 
kernel: Linux localhost 3.8.11 #1 SMP Wed May 11 22:25:37 PDT 2016 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
No Chromium OS X server is available.
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
xfce4-session: No gpg or ssh authentication agent found
/usr/bin/xbindkeys_autostart: line 24: CONF: unbound variable

(polkit-gnome-authentication-agent-1:26566): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

(polkit-gnome-authentication-agent-1:26566): polkit-gnome-1-WARNING **: Failed to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
Timeout waiting for extension(II) AIGLX: Suspending AIGLX clients for VT switch
Error: target STRING not available
croutonwebsocket error: EError: not connected.

**Comment by jejones3141** [comment]
Tried redirecting stdout and stderr to a file to see if that would help,
but it showed up on the screen anyway. Is

    sudo starte17 >~/Downloads/errs.txt 2>&1

not the way to do that, perhaps?

**Comment by kkelley515** [comment]
Just saw there was a chromeOS upgrade available (v. 50 to v. 51). The upgrade seemed to solve the issue for me (HP chromebook 14, chroot is trusty with xfce).

**Comment by jejones3141** [comment]
So far, so good; v.51 is not showing the problem for me. Thanks, kkelley515!

**Comment by shwnchpl** [comment]
Ever since I switched to beta this issue has been solved for me, but recently I've been having another issue which I think may be related.  When I switch from crouton back to Chrome, my touchpad stops functioning in the way it should and starts functioning as though it were being double touched (instead of moving the cursor icon, the touchpad scrolls windows up and down, etc).  Sometimes behavior reverts to normal but other times it doesn't until reboot, even after I've shut down crouton.  Has anyone else been experiencing this?

**Comment by keithfarvis** [comment]
Fixed for me on Acer C720. It seemed to get fixed for me last week before any ChromeOS update.  It is still OK now having had a ChromeOS update to V51 on the stable channel.  Thank goodness, the flashing was very disruptive.

**Comment by Kalirren** [comment]
Seems to have been fixed for me upon ChromeOS update to v. 51. It was still happening to me before I forced the update.

**Comment by acowley** [comment]
V51 fixed it for me, too.

**Comment by djreiss** [comment]
Likewise, this is now resolved for me after updating to v51.

**Comment by wkhalidman2** [comment]
solved now. Finally!

**Comment by kajodowe** [comment]
Hi all -- I started this thread a little over a month ago. In reading the posts to date, it appears that the solution for most people revolved around upgrading to v51 of the Chrome OS, either on the Stable or Beta channel. That worked for me as I have not seen any flicker at all for weeks now. All is well!

**Comment by patitude29** [comment]
Odd, I hadn't had a problem but now that I'm on v51 it's flashing back and forth between xfce and chrome.

**Comment by flactemnad** [comment]
On my Acer C720P I've switched back from beta to stable, currently running Version 51.0.2704.79 (64-bit), and my system has been stable.  Beta v51 was also stable for me.
(Switching from the beta channel back to stable was accomplished without a powerwash by using this command: 
   sudo update_engine_client --channel=stable-channel --nopowerwash
I did make a full backup prior to that just in case.  When rebooting, the system warned of a powerwash, but it didn't actually happen.)

**Comment by wkhalidman2** [comment]
That command is awesome!

**Comment by dnschneid** [comment]
OK, sounds like a "transient" (6-week-long) problem on the stable channel.  Sorry for the downtime...

**Comment by floe** [comment]
Actually, this (or a very similar problem) seems to be still around: I'm on v52 from the beta channel now, and I can switch back and forth between XFCE and Chromium OS just fine - as long as the device doesn't sleep in the meantime. In that case, when I try to switch to XFCE, I get a black screen with a frozen mouse cursor and have to hard-reset (hold power button for 10s).
