### ISSUE TITLE
Post v53 dev-channel on veyron_minnie

### ISSUE THREAD

**Issue by blends** [dnschneid/crouton#2632]
v53.0.2768.0
dev-channel veyron_minnie

When attempting to install a new chroot using sudo sh crouton -r trusty -t core,audio,cli-extra,xorg,x11,gtk-extra,extension,keyboard,touch,xfce,xiwi
```
Base system installed successfully.
Pruning /mnt/stateful_partition/crouton/chroots/trusty mounts...
Creating hwaudio group with GID 18...
groupadd: failure while writing changes to /etc/group
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```
```
chronos@localhost /usr/local/bin $ sudo edit-chroot -all
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
Creating hwaudio group with GID 18...
groupadd: failure while writing changes to /etc/group
```

**Comment by hasanin** [comment]
yes I am facing the same issue with my asus flip,, crouton was working fine with chrome os stable channel, recently I wiped out my chrome and re accessed the developer mode and switched to dev channel - the main reason is to receive android play updates which happened - after that I have been trying to install and run crouton with no luck, I tried many distros-environments mixtures with no luck, the installation doen't complete at all, errors are:
```
Pruning /mnt/stateful_partition/crouton/chroots/trusty mounts...
Creating hwaudio group with GID 18...
groupadd: failure while writing changes to /etc/group
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
```
or
```
Removing x11proto-xext-dev ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Please specify a username for the primary user: ahmed
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
```
I am guessing this is related to the recent update.

**Comment by rbpaul** [comment]
I am getting the same error on my ASUS Flipbook after upgrading to v53.0.2768.0
dev-channel veyron_minnie

**Comment by tista500** [comment]
Greetings,

I'm also facing similar issues when running `sudo sh ~/Downloads/crouton -u` (updating crouton)...
In my case, my xenial failed to launch Xorg caused by SELinux?
* dbus: seems to fail to load `/etc/selinux/targeted/contexts/dbus_contexts.conf`?
* xorg: seems to fail to load `/etc/selinux/targeted/contexts/x_contexts.conf`?

Anyway those configuration files are not bundled with default chroot setup, and I've tried to make those by hand, no luck (dbus error was fixed but xorg needs some more love)...

Regards.

**Comment by aivijay** [comment]
Yes, I am also having problems with Asus flip with the upgrade to the dev channel. Used to work fine with trusty a couple of days back atleast.

**Comment by rbpaul** [comment]
I: Base system installed successfully.
Pruning /media/removable/SD Card/chroots/trusty mounts...
Creating hwaudio group with GID 18...
**groupadd: failure while writing changes to /etc/group**
Unmounting /media/removable/SD Card/chroots/trusty...
chronos@localhost ~ $ I: Base system installed successfully.
bash: I:: command not found
chronos@localhost ~ $ Pruning /media/removable/SD Card/chroots/trusty mounts...
bash: Pruning: command not found
chronos@localhost ~ $ Creating hwaudio group with GID 18...
bash: Creating: command not found
chronos@localhost ~ $ groupadd: failure while writing changes to /etc/group
bash: groupadd:: command not found
chronos@localhost ~ $ Unmounting /media/removable/SD Card/chroots/trusty...
bash: Unmounting: command not found
chronos@localhost ~ $ 

Is this a problem with Crouton? of Chrome?  Any way to proceed?

**Comment by drinkcat** [comment]
This should fix it: #2612.

**Comment by rbpaul** [comment]
drinkcat

That fix didn't work for me - after applying it, I am still getting 
"Unable to Execute - Permission denied" messages

Any other suggestions?  

Thanks

**Comment by DennisLfromGA** [comment]
@rbpaul,

Are you're getting a different error message now?
> "Unable to Execute - Permission denied" messages

instead of the earlier ones?
> groupadd: failure while writing changes to /etc/group

Did you add the routine in the PR to enter-chroot at lines 531-534 before you tried it again?
Did the crouton install complete successfully?

Curious,
-**DennisL**

**Comment by dnschneid** [comment]
I just merged #2612, so the original issue here should be fixed (please reopen if it's not).

@rbpaul: if you're now getting a different error message, please open a new issue.

**Comment by rbpaul** [comment]
Thanks, but it is not yet fixed for me.

I get this error when trying to install a chroot: groupadd: "failure while writing changes to /etc/group"  The system first says the " Base system installed successfully", and I can see it on my SDCard, but I can't mount or enter the chroot either before or after adding the routine in the PR to enter-chroot at lines 531-534.  When I do try to mount or enter the chroot that is when I get the "Unable to Execute - Permission denied" messages.

So if you have anything for that, please let me know.

**Comment by dnschneid** [comment]
Can you try grabbing the latest release and running it unmodified?

**Comment by hasanin** [comment]
fix https://github.com/dnschneid/crouton/pull/2612/commits/3454f13e4b1f1e0ae5e0db03d57c7302814fa2ea
indeed worked fine with me.

**Comment by rbpaul** [comment]
With the latest release - I have successfully installed the chroot and can mount and enter it.

Thank you
