### ISSUE TITLE
Chromebook Plus fails when mounting chroot

### ISSUE THREAD

**Issue by ibsusu** [dnschneid/crouton#3069]
``` cat /etc/lsb-release
CHROMEOS_ARC_VERSION=3698271
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={92A7272A-834A-47A3-9112-E8FD55831660}
CHROMEOS_RELEASE_BOARD=kevin-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=83
CHROMEOS_RELEASE_BUILDER_PATH=kevin-release/R56-9000.83.0
CHROMEOS_RELEASE_BUILD_NUMBER=9000
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=56
CHROMEOS_RELEASE_DESCRIPTION=9000.83.0 (Official Build) stable-channel kevin 
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=9000.83.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=9000.83.0
```

#### Please describe your issue:
```install log
umount: /sys/fs/cgroup: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
I: Keyring file not available at /usr/share/keyrings/ubuntu-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
W: Failure trying to run:  mount -t sysfs sysfs /sys
W: See //debootstrap/debootstrap.log for details
Failed to complete chroot setup.
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
```
The same thing happens for the normal supported release.

#### If known, describe the steps to reproduce the issue:
1. Just follow the install steps in the examples with a Samsung Chromebook Plus.

**Comment by ibsusu** [comment]
when I did `lsof` I got the following output.  Does this mean crouton is going to have a problem with android?
```
chronos@localhost / $ lsof +f --  /sys/fs/cgroup
lsof: WARNING: can't stat() tracefs file system /sys/kernel/debug/tracing
      Output information may be incomplete.
lsof: WARNING: can't stat() squashfs file system /opt/google/containers/android/rootfs/root
      Output information may be incomplete.
lsof: WARNING: can't stat() squashfs file system /opt/google/containers/android/rootfs/root/vendor
      Output information may be incomplete.
lsof: WARNING: can't stat() squashfs file system /opt/google/containers/arc-downloads-filesystem/mountpoints/container-root
      Output information may be incomplete.
lsof: WARNING: can't stat() squashfs file system /opt/google/containers/arc-removable-media/mountpoints/container-root
      Output information may be incomplete.
lsof: WARNING: can't stat() squashfs file system /opt/google/containers/arc-sdcard/mountpoints/container-root
      Output information may be incomplete.
lsof: WARNING: can't stat() squashfs file system /opt/google/containers/arc-obb-mounter/mountpoints/container-root
      Output information may be incomplete.
lsof: WARNING: can't stat() ecryptfs file system /home/.shadow/ef8f52505c997278bb4cfa1d6ddfac212b8c7368/mount
      Output information may be incomplete.
lsof: WARNING: can't stat() ecryptfs file system /opt/google/containers/android/rootfs/android-data
      Output information may be incomplete.
lsof: WARNING: can't stat() ext2 file system /opt/google/containers/arc-downloads-filesystem/mountpoints/android-downloads-shared
      Output information may be incomplete.
lsof: WARNING: can't stat() squashfs file system /run/containers/android_qgG9iO/root
      Output information may be incomplete.
lsof: WARNING: can't stat() ecryptfs file system /run/containers/android_qgG9iO/root/cache
      Output information may be incomplete.
lsof: WARNING: can't stat() ecryptfs file system /run/containers/android_qgG9iO/root/data
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/dev
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/dev/dri
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/dev/input
      Output information may be incomplete.
lsof: WARNING: can't stat() devpts file system /run/containers/android_qgG9iO/root/dev/pts
      Output information may be incomplete.
lsof: WARNING: can't stat() devpts file system /run/containers/android_qgG9iO/root/dev/ptmx
      Output information may be incomplete.
lsof: WARNING: can't stat() ext4 file system /run/containers/android_qgG9iO/root/dev/kmsg
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/oem
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/var/run/arc
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/var/run/anr
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/var/run/arc/bugreport
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/var/run/camera
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/var/run/chrome
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /run/containers/android_qgG9iO/root/var/run/cras
      Output information may be incomplete.
lsof: WARNING: can't stat() squashfs file system /run/containers/android_qgG9iO/root/vendor
      Output information may be incomplete.
lsof: WARNING: can't stat() fuse file system /opt/google/containers/arc-downloads-filesystem/mountpoints/android-downloads-shared/dlfs
      Output information may be incomplete.
```

**Comment by ibsusu** [comment]
I've gotten past this sticking point by just doing `unmount -l /sys/fs/cgroup`  to force it but I'm now I'm dealing with a different issue.  Xenial didn't work, currently trying default.

**Comment by ibsusu** [comment]
The point I'm getting stuck at seems to be the first prompt with the default install with touch,xfce as targets
```
The following packages will be REMOVED:
  libasound2-dev* libdrm-dev* libdrm-omap1* libpthread-stubs0* libpthread-stubs0-dev* libspeex-dev* libspeex1* libspeexdsp-dev* libx11-dev* libxau-dev* libxcb1-dev* libxdmcp-dev* libxext-dev*
  libxfixes-dev* libxi-dev* patch* pkg-config* x11proto-core-dev* x11proto-fixes-dev* x11proto-input-dev* x11proto-kb-dev* x11proto-xext-dev* xorg-sgml-doctools* xtrans-dev*
0 upgraded, 0 newly installed, 24 to remove and 0 not upgraded.
After this operation, 9369 kB disk space will be freed.
(Reading database ... 40924 files and directories currently installed.)
Removing libasound2-dev ...
Removing libdrm-dev ...
Removing libdrm-omap1 ...
Purging configuration files for libdrm-omap1 ...
Removing libxi-dev ...
Removing libxfixes-dev ...
Removing libxext-dev ...
Removing libx11-dev ...
Removing libxcb1-dev ...
Removing libpthread-stubs0-dev ...
Removing libpthread-stubs0 ...
Removing libspeexdsp-dev ...
Removing libspeex-dev ...
Removing libspeex1 ...
Purging configuration files for libspeex1 ...
Removing libxau-dev ...
Removing libxdmcp-dev ...
Removing patch ...
Removing pkg-config ...
Removing x11proto-fixes-dev ...
Removing x11proto-xext-dev ...
Removing x11proto-input-dev ...
Removing x11proto-core-dev ...
Removing x11proto-kb-dev ...
Removing xorg-sgml-doctools ...
Removing xtrans-dev ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
Please specify a username for the primary user: billybobtestname
Failed to complete chroot setup.
The chroot setup script may be broken. Your chroot is not fully configured.
Removing the chroot setup script. You may want to update your chroot again.
UID 1000 not found in precise
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost ~ $ 
```

There's nothing really telling in this error.  Maybe I missed something?

**Comment by ibsusu** [comment]
I can't seem to get either unity or xfce working.  I settled for just having xenial and the cli working :(

If anyone else gets further than me I'd like to know

**Comment by BWoodson** [comment]
I've also had this issue with crouton on the Chromebook Plus. Running unmount -l /sys/fs/cgroup was able to let me install cli-extra which is all I need. Once installed the only issue I've been having so far is getting node to install through nvm. Still working on solving that one.

**Comment by dnschneid** [comment]
@ibsusu: are you trying to install xenial or precise?  What commands are you using?

**Comment by ibsusu** [comment]
Here is the command that worked:
`sudo sh ~/Downloads/crouton -r xenial -t cli-extra`

Here are the commands that didn't:
```
sudo sh ~/Downloads/crouton -t touch,xfce
sudo sh ~/Downloads/crouton -t xfce
sudo sh ~/Downloads/crouton -t xfce -r xenial
sudo sh ~/Downloads/crouton -t touch,xfce -r xenial
```

The print out in this comment https://github.com/dnschneid/crouton/issues/3069#issuecomment-279296815 was produced during this command: `sudo sh ~/Downloads/crouton -t xfce`

I cleared the cache during each attempt and removed the chroot directory before each attempt with the  `rm -rf /tmp/crouton-installer-cache/crouton` and `sudo rm -rf /usr/local/chroots/xenial/` or  `sudo rm -rf /usr/local/chroots/precise/` commands respectively.

**Comment by dnschneid** [comment]
I repro'd easily on my plus.  Looks like there's a new mount `/sys/fs/cgroup/schedtune/chrome` that isn't caught by the recursive unmounter in /prepare.sh, since it has `-maxdepth 2`.

Either we need to increase -maxdepth to 3 or use code more similar to unmount-chroot for finding the mounts inside of /sys

**Comment by dnschneid** [comment]
Setting maxdepth to 3 doesn't work either, since it hits invalid files.  This seems like a really flaky way to recursively unmount /sys inside the chroot, so it seems the approach in unmount-chroot needs to be used instead.

**Comment by dnschneid** [comment]
Okay, the latest crouton should fix this issue.

**Comment by ibsusu** [comment]
totally works. By any chance would you know why I can't get past the second point though?

**Comment by dnschneid** [comment]
Can you file another bug for that, please?

**Comment by ibsusu** [comment]
Done, thank you.

**Comment by TheTonyStarks** [comment]
@dnschneid, what was the fix?

**Comment by dnschneid** [comment]
Fix for this was in 9907766eacd100c24adb011588d4125c112d11c4.  The additional issue of useradd failing on precise isn't fixed yet.
