### ISSUE TITLE
Samsung Chromebook Plus - startxfce4 causes reboot 

### ISSUE THREAD

**Issue by gazidoc** [dnschneid/crouton#3195]
Please paste the output of the following command here: sudo edit-chroot -all
``name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170315143304~master:95589555
release: xenial
architecture: arm64
xmethod: xorg
targets: x11,xfce,touch,keyboard,extension
host: version 9413.0.0 (Official Build) dev-channel kevin 
kernel: Linux localhost 4.4.52-07972-gf27275748d2d #1 SMP PREEMPT Wed Mar 29 19:03:23 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...`

#### Please describe your issue:
Previously working system reduced to black screen and reboot when X11 needed to run.

#### If known, describe the steps to reproduce the issue:
Previous to this Google update my chromebook plus was working with xenial and xfce. Following the update, issuing the command "sudo startxfce4" causes a non-recoverable black screen proceeded about 30 seconds later by a reboot. I have tried power washing, re-installing xenial, as well as using different distros and targets - trusty, precise and zesty: same result. "startcli" works suggesting X11 problem. I see other issues with X11 but no one has reported a reboot.

**Comment by maxbob01** [comment]
me too

**Comment by hugoShaka** [comment]
The last chromeOS update also broke X11 for me.
Using the HP Chromebook 14, the arm64 one.
Here is the error log on a fresh chroot (trusty, x11 target only, i3 installed and xinit).

[trusty_crouton_x11_log.txt](https://github.com/dnschneid/crouton/files/909771/trusty_crouton_x11_log.txt)

Something changed in the way chromeOS handles the screen and the chroots don't detect it anymore. I will test the xiwi target later.

**Comment by coderhyder** [comment]
I am running the same command on my samsung with intel, and having the same problem: CLI: sudo startxfce4 ;;; Then It tries to book, goes to black. SHIFT + ALT + FWD does nothing: which key is FWD, or BACK...?

**Comment by coderhyder** [comment]
I am still quite new at this so...if I am doing something wrong let me know, There is always another path.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> ; )

chronos@localhost ~/Downloads $ sudo enter-chroot startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
WARNING: starting chroot system dbus daemon failed with code 1
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-75-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.18.0-13753-gc65690b #1 SMP PREEMPT Tue Mar 28 23:37:52 PDT 2017 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3584000 verity payload=PARTUUID=f37d1afa-50b8-c048-8794-67cbdb7bcd9b/PARTNROFF=1 hashtree=PARTUUID=f37d1afa-50b8-c048-8794-67cbdb7bcd9b/PARTNROFF=1 hashstart=3584000 alg=sha1 root_hexdigest=547b0c6304ac0f9e49ec5ff930b2e27351608671 salt=a89149d641b7f2698f2e1f6b88c7f1d533d72b9ce93dde674368aec128ac7c92" noinitrd vt.global_cursor_default=0 kern_guid=f37d1afa-50b8-c048-8794-67cbdb7bcd9b add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic  
Build Date: 12 February 2015  03:37:52PM
xorg-server 2:1.15.1-0ubuntu2~precise5 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Wed Apr 12 22:48:42 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
setversion 1.4 failed: Permission denied
Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension SECURITY
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension XFree86-VidModeExtension
Initializing built-in extension XFree86-DGA
Initializing built-in extension XFree86-DRI
Initializing built-in extension DRI2
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[intel_init_bufmgr:1069] Error initializing buffer manager.
setversion 1.4 failed: Permission denied
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9202.60.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-13753-gc65690b #1 SMP PREEMPT Tue Mar 28 23:37:52 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
EOF in dbus-launch reading address from bus daemon
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found
Loading extension GLX
xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[intel_init_bufmgr:1069] Error initializing buffer manager.
setversion 1.4 failed: Permission denied
crouton: version 1-20161129162558~master:5f2f11f9
release: precise
architecture: amd64
xmethod: xorg
targets: xfce
host: version 9202.60.0 (Official Build) stable-channel celes 
kernel: Linux localhost 3.18.0-13753-gc65690b #1 SMP PREEMPT Tue Mar 28 23:37:52 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux
freon: yes
Failed to start message bus: Failed to open "/etc/selinux/targeted/contexts/dbus_contexts": No such file or directory
EOF in dbus-launch reading address from bus daemon
/etc/xdg/xfce4/xinitrc: 1: /etc/xdg/xfce4/xinitrc: ssh-agent: not found^C/usr/bin/xinit: connection to X server lost

waiting for X server to shut down xscreensaver: 22:50:14: SIGHUP received: restarting...
xscreensaver: 22:50:14: running as coderhyder/coderhyder (1000/1000)

Hangup
Hangup
Running exit commands...
(EE) Server terminated successfully (0). Closing log file.
xscreensaver: 22:50:14: Can't open display: :1
xscreensaver: 22:50:14: running as coderhyder/coderhyder (1000/1000)

xscreensaver: 22:50:14: Errors at startup are usually authorization problems.
              But you're not logging in as root (good!) so something
              else must be wrong.  Did you read the manual and the FAQ?

              http://www.jwz.org/xscreensaver/faq.html
              http://www.jwz.org/xscreensaver/man.html


/usr/bin/xinit: unexpected signal 2
Unmounting /mnt/stateful_partition/crouton/chroots/precise...
chronos@localhost ~/Downloads $ ^C
chronos@localhost ~/Downloads $

**Comment by gazidoc** [comment]
According to your screen grab you typed 'sudo enter-chroot startxfce4', not 'sudo startxfce4' at the shell prompt. I'm not sure if this is the same problem.

**Comment by danharris923** [comment]
me too,  my old chroot, backups and a brand new one all halt and restart when x starts.

heres my facts.  chrome is stable nyan blaze  57.0.2987.146.  crouton was updated. all my chroots are trusty and xfce.  computer is an hp14?  its got a nvidia tegra chip. arm

**Comment by gazidoc** [comment]
"Fixed".
I was on dev channel.
Change to stable channel. Go into developer mode.
Re-installed everything. Now working. Welcome back Ubuntu!

**Comment by kpalian** [comment]
I have this same issue and changing to stable channel didn't fix anything. Anybody got any other suggestions?

**Comment by battlemidget** [comment]
This shouldnt be closed as other people (including myself) are running into this same issue.

**Comment by DennisLfromGA** [comment]
@battlemidget and others,

Please at least show us the output of: `sudo edit-chroot -all`
Then we'll know what releases and targets are involved.

Also, is this reboot happening only on the SCB+ and only with the xfce target?

-**DennisL**

**Comment by crony1** [comment]
I'm on a Samsung Chromebook Plus.  It's happening on xfce and lxde:

chronos@localhost / $ sudo edit-chroot -all
name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: arm64
xmethod: xorg
targets: lxde
host: version 9460.60.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.52-08254-ge4cd28825ca4 #1 SMP PREEMPT Mon Jun 5 16:59:00 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by cd109876** [comment]
Same problem with kde on CB+ on stable channel
sudo edit-chroot -all

name: xenial
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/xenial...
crouton: version 1-20170619181610~master:980f090f
release: xenial
architecture: arm64
xmethod: xorg
targets: touch,kde
host: version 9460.73.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.52-08273-ge6c7193d61d7 #1 SMP PREEMPT Thu Jul 13 12:07:57 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by DennisLfromGA** [comment]
@battlemidget, @crony1, @cd109876, and others,

This looks to be confined to the 'xorg' xmethod but, as an experiment, could one or more of you please add and test the 'xiwi' xmethod just to be sure?

*Thanx,*
-**DennisL**

**Comment by cd109876** [comment]
Yes, xiwi works. I had to manually install xserver-xorg-core and xserver-xorg-video-dummy first or xiwi would fail to install.

**Comment by DennisLfromGA** [comment]
@cd109876,

Thanx for trying 'xiwi' and reporting your results.
It's not a perfect solution but it may be a workaround until the issue can be fixed at least.
Unfortunately, I don't have a SCB+ so I can't troubleshoot it but maybe the devs or others can find a way.

*Hope this helps,*
-**DennisL**

**Comment by rbutera** [comment]
Same issues as this thread.  The above comment helped immensely -- startxfce only works with xiwi, and xiwi required a manual install of the above two aforementioned packages.  Also on a Chromebook Plus.

**Comment by hugoShaka** [comment]
I had the same problem when using the xorg target on my ARMv7 chromebook HP 14.
For me it works when using only target x11 (like in https://github.com/dnschneid/crouton/wiki/i3) but I can't change tty with ctrl+alt+f1. I hope it'll help you.

**Comment by RNYSC** [comment]
@rbutera Very new to this, how did you manually install the two packages?

Thanks.

**Comment by rbutera** [comment]
I think I used the -f flag on apt-get.  I honestly cannot remember!
