### ISSUE TITLE
Cannot get Linux xfce4 to run on Samsung Chromebook Plus for the life of me

### ISSUE THREAD

**Issue by 04deoxys** [dnschneid/crouton#3374]
```
Please paste the output of the following command here: sudo edit-chroot -all
```
name: trusty
encrypted: no
Entering /mnt/stateful_partition/crouton/chroots/trusty...
crouton: version 1-20170825164243~master:6af640de
release: trusty
architecture: arm64
xmethod: xorg
targets: xfce
host: version 9592.85.0 (Official Build) stable-channel kevin 
kernel: Linux localhost 4.4.64-09100-g30321742b4e0 #1 SMP PREEMPT Mon Aug 21 20:02:10 PDT 2017 aarch64 aarch64 aarch64 GNU/Linux
freon: yes
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...
#### Please describe your issue:
I am having some serious issues with installing xfce4 on my chromebook. So far, the first attempt was actually with Unity. But every time I tried running it, the screen would go black for a solid minute, then the computer would reboot. So then I tried working with xfce4, and I continuously get this error:

Entering /mnt/stateful_partition/crouton/chroots/trusty...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

X.Org X Server 1.15.1
Release Date: 2014-04-13
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-83-generic aarch64 Ubuntu
Current Operating System: Linux localhost 4.4.64-09100-g30321742b4e0 #1 SMP PREEMPT Mon Aug 21 20:02:10 PDT 2017 aarch64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 3334144 verity payload=PARTUUID=82649190-1d1d-314b-8477-4062e6dc7c29/PARTNROFF=1 hashtree=PARTUUID=82649190-1d1d-314b-8477-4062e6dc7c29/PARTNROFF=1 hashstart=3334144 alg=sha1 root_hexdigest=f7419c96d47e2cecef3dc3b07a2755edc322cb49 salt=4babd4b8f4ee2622e91395c026d5fa21fa6f6246faf68ec3104c18ceb3549de1" noinitrd vt.global_cursor_default=0 kern_guid=82649190-1d1d-314b-8477-4062e6dc7c29  
Build Date: 20 July 2017  07:12:02PM
xorg-server 2:1.15.1-0ubuntu2.9 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.1.log", Time: Mon Aug 28 21:02:54 2017
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
(EE) Backtrace:
(EE) 0: /usr/bin/Xorg (xorg_backtrace+0x44) [0x59a148cc94]
(EE) 
(EE) Segmentation fault at address 0x0
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/trusty...

I have looked all over the internet for a solution, but the ones I've attempted have not worked at all.
I've updated, re-installed the entire thing, I've done the rm /dev/dir/card0 method only to be greeted with yet another error until I reboot:

chronos@localhost / $ sudo rm /dev/dir/card0
Password: 
rm: cannot remove '/dev/dir/card0': No such file or directory

There was also another error I can't recall after typing in the full command, something to do with a missing directory yet again.

I'm all out of ideas. Unity doesn't work, xfce4 doesn't work, what other solution is there? I am trying to run emulation off my chromebook, at this point I think I'm better off just getting the emulator off the actual app store on the computer.

Please, someone help me with this issue, I've tried every possible solution and have searched countless forums for one that works.

**Comment by icecream95** [comment]
Unity doesn't work on the Chromebook Plus as Unity requires OpenGL, which is not available on ARM Chromebooks such as the Samsung Chromebook Plus.

Your problem with other desktop environments lies in a spelling error:
It is supposed to be `/dev/dri/card0`, not `/dev/dir/card0`.

**Comment by 04deoxys** [comment]
Well, that was a typo on behalf of typing this post, and I do apologize for that. But, I have been typing that in this whole time only to be greeted with 

Entering /mnt/stateful_partition/crouton/chroots/xenial...
mv: cannot stat '/run/crouton/mnt/stateful_partition/crouton/chroots/xenial/run/dri/card*': No such file or directory
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...

**Comment by Derpjohn** [comment]
i have the same issue
been trying all of the suggestions on the forums for a few days now.

**Comment by icecream95** [comment]
What happens if you try this before trying to start a desktop environment?

    sudo enter-chroot
    sudo rm /dev/dri/card0
    sudo mv /dev/dri/card1 /dev/dri/card0
    exit

**Comment by 04deoxys** [comment]
xenial)deoxys@localhost:~$ sudo rm /dev/dri/card0
[sudo] password for deoxys: 
(xenial)deoxys@localhost:~$ sudo mv /dev/dri/card1 /dev/dri/card0
mv: cannot stat '/dev/dri/card1': No such file or directory
(xenial)deoxys@localhost:~$

**Comment by icecream95** [comment]
You could try installing the xiwi target (replace CHROOTNAME with the name of your chroot):

`sudo sh -e ~/Downloads/crouton -u -t xiwi -n CHROOTNAME`

Then, install the [Crouton Integration](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom) extension, and you should be able to start XFCE (or other desktop environments) normally, without any `rm /dev/dri/card0` stuff.

**Comment by serfma** [comment]
I'm having the same exact issue of using xorg resulting in a black screen and rebooting. (CB+, of course) Xiwi works perfectly fine and it has been a couple months since I last successfully was able to use xorg.

**Comment by 04deoxys** [comment]
The issue was resolved!

Did a complete power wash of the computer, and I believe since I had an SD Card in the slot, everything got rooted onto there and wouldn't run. I could be wrong, someone gave a better explanation. Anyhow, closing this thread.

**Comment by ksrini7** [comment]
After installing crouton with xfce when entered 
sudo startxfce4 in samsung chromebook
and
following above advice it did not resolve and the problem did not solve and got the following error and t
 
Enter encryption passphrase for xenial: 
Entering /mnt/stateful_partition/crouton/chroots/xenial...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.19.6
Release Date: 2017-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-128-generic armv7l Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Mon Jun 25 22:09:26 PDT 2018 armv7l
Kernel command line: cros_secure console= console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2539520 verity payload=PARTUUID=ea6b08c8-c6d1-c845-97e2-af13b302ab79/PARTNROFF=1 hashtree=PARTUUID=ea6b08c8-c6d1-c845-97e2-af13b302ab79/PARTNROFF=1 hashstart=2539520 alg=sha1 root_hexdigest=1d84f4beeaa945c2a4a7a9c357c9c313cc443fe5 salt=cf877d6d1c1abd72761248b7eee1eb073b44e8383ad44290182803bee841b0da" noinitrd vt.global_cursor_default=0 kern_guid=ea6b08c8-c6d1-c845-97e2-af13b302ab79  
Build Date: 14 June 2018  05:10:24PM
xorg-server 2:1.19.6-1ubuntu4~16.04.1 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.33.6
        Before reporting problems, check http://wiki.x.org
for help. 
(EE) Please also check the log file at "/tmp/Xorg.crouton.1.log" for additional information.
(EE) 
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.chromium.LibCrosService was not provided by any .service files
method return time=1531114181.801620 sender=:1.11 -> destination=:1.59 serial=1190 reply_serial=2
   boolean true
(EE) Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: Connection refused
/usr/bin/xinit: server error
Unmounting /mnt/stateful_partition/crouton/chroots/xenial...
chronos@localhost ~ $ Enter encryption passphrase for xenial:

**Comment by ksrini7** [comment]
![screenshot 2018-07-09 at 11 00 02 am](https://user-images.githubusercontent.com/40976834/42432466-4a649f86-8368-11e8-9a15-3f7cd2ef4952.png)

**Comment by ksrini7** [comment]
Solved
I installed trusty it worked

Now struggling to install Libre office
